title: Avery P. Hill
author:
  name: Avery Hill
  email: apaytonhill@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings

theme: minima

destination: docs/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

# To add social links, resize custom .svg to 16x16 with https://www.iloveimg.com/
# And then strip everything except for the <path></> tag, and add it to _include/social-icons

  # Generate social links in footer.
  #
  social_links:
    - { platform: cv,          user_url: "/assets/documents/cv.pdf" }
    - { platform: inaturalist,          user_url: "https://www.inaturalist.org/people/avephill" }
    - { platform: github,         user_url: "https://github.com/avephill" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=ZulkVO0AAAAJ&hl" }
    - { platform: mastodon,      user_url: "https://ecoevo.social/@avephill" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/avery-hill-phd-547099197" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
